name: Print Environment Variables

on: [push]

jobs:
  print-env:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print environment variables
      run: |
        echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
       
